version: '3'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3307:5432"